# Generated by Django 5.0.6 on 2024-07-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
