# Generated by Django 5.1.1 on 2024-11-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default=1, max_length=250, verbose_name='موضوع'),
            preserve_default=False,
        ),
    ]
