# Generated by Django 5.1.2 on 2024-11-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ticket_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
