# Generated by Django 5.1.2 on 2024-11-21 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(help_text='شماره تلفن باید 11 رقم باشد', max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و جمعا 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
